# Generated by Django 4.1.7 on 2023-05-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='videofile',
        ),
        migrations.RemoveField(
            model_name='video',
            name='photo',
        ),
    ]
